Test `gcc@11` install on older Ubuntu.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,7 +10,8 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [macos-10.15, macos-11, macos-12, ubuntu-20.04, ubuntu-22.04]
+        os: [ubuntu-18.04, ubuntu-20.04]
+        trial: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
       fail-fast: false
     steps:
       - name: Set up Homebrew
@@ -19,6 +20,9 @@ jobs:
       - name: Checkout `master`
         run: git -C "$(brew --repository)" checkout master
 
+      - name: Uninstall everything.
+        run: brew uninstall $(brew list)
+
       - name: Show `brew --version`.
         run: |
           printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
@@ -26,16 +30,13 @@ jobs:
           printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
           printf '```\n' >> "$GITHUB_STEP_SUMMARY"
 
-      - name: Show `hello` dep tree
+      - name: Install `gcc@11`.
         run: |
-          printf '### `brew deps hello` output\n' >> "$GITHUB_STEP_SUMMARY"
-          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
-          printf '%s\n' "$(brew deps hello)" | tee -a "$GITHUB_STEP_SUMMARY"
-          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
-
-      - name: Run `brew info hello`.
-        run: |
-          printf '### `brew info hello` output\n' >> "$GITHUB_STEP_SUMMARY"
-          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
-          printf '%s\n' "$(brew info hello)" | tee -a "$GITHUB_STEP_SUMMARY"
-          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
+          printf '## Trial ${{ matrix.trial }} on ${{ matrix.os }} :test_tube:'
+          if brew install gcc@11
+          then
+            printf 'success! :tada:n' >> "$GITHUB_STEP_SUMMARY"
+          else
+            printf 'failed :cry:\n' >> "$GITHUB_STEP_SUMMARY"
+            exit 1
+          fi
